# Generated by Django 5.2 on 2025-10-25 14:58

from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Contact",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField()),
                ("email", models.EmailField(max_length=254)),
                ("message", models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name="Education",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("institution", models.CharField()),
                ("degree", models.CharField()),
                ("field_of_study", models.CharField()),
                ("description", models.TextField(blank=True)),
                ("start_date", models.DateField()),
                ("end_date", models.DateField(blank=True, null=True)),
            ],
            options={
                "ordering": ["-start_date"],
            },
        ),
        migrations.CreateModel(
            name="Interest",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "ordering",
                    models.PositiveIntegerField(
                        db_index=True, default=0, verbose_name="ordering"
                    ),
                ),
                ("name", models.CharField(unique=True)),
                ("description", models.TextField(blank=True)),
            ],
            options={
                "ordering": ["ordering"],
                "abstract": False,
            },
        ),
        migrations.CreateModel(
            name="Job",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField()),
                ("company", models.CharField()),
                ("location", models.CharField()),
                ("description", models.TextField()),
                ("date_started", models.DateField()),
                ("date_ended", models.DateField(blank=True, null=True)),
            ],
            options={
                "ordering": ["-date_started"],
            },
        ),
        migrations.CreateModel(
            name="Project",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "ordering",
                    models.PositiveIntegerField(
                        db_index=True, default=0, verbose_name="ordering"
                    ),
                ),
                ("name", models.CharField(unique=True)),
                ("description", models.TextField()),
                ("url", models.URLField(blank=True)),
                ("repository_url", models.URLField(blank=True)),
                ("image", models.CharField(blank=True)),
                ("technologies", models.JSONField(blank=True, default=list)),
            ],
            options={
                "ordering": ["ordering"],
                "abstract": False,
            },
        ),
        migrations.CreateModel(
            name="Skill",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "ordering",
                    models.PositiveIntegerField(
                        db_index=True, default=0, verbose_name="ordering"
                    ),
                ),
                ("name", models.CharField()),
                ("proficiency", models.CharField()),
            ],
            options={
                "ordering": ["ordering"],
                "abstract": False,
            },
        ),
    ]
