# Generated by Django 5.2 on 2025-10-26 03:37

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("portfolio", "0002_education_is_published_interest_is_published_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="skill",
            name="proficiency",
            field=models.IntegerField(
                validators=[
                    django.core.validators.MinValueValidator(0),
                    django.core.validators.MaxValueValidator(10),
                ]
            ),
        ),
    ]
