# Generated by Django 5.2 on 2025-10-27 02:56

import django_jsonform.models.fields
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("portfolio", "0003_alter_skill_proficiency"),
    ]

    operations = [
        migrations.RenameModel(
            old_name="Skill",
            new_name="Technology",
        ),
        migrations.AlterModelOptions(
            name="job",
            options={"ordering": ["-start_date"]},
        ),
        migrations.RenameField(
            model_name="job",
            old_name="date_ended",
            new_name="end_date",
        ),
        migrations.RenameField(
            model_name="job",
            old_name="date_started",
            new_name="start_date",
        ),
        migrations.AddField(
            model_name="education",
            name="highlights",
            field=django_jsonform.models.fields.ArrayField(
                base_field=models.CharField(), blank=True, default=list, size=None
            ),
        ),
        migrations.AddField(
            model_name="education",
            name="location",
            field=models.CharField(blank=True),
        ),
        migrations.AddField(
            model_name="job",
            name="highlights",
            field=django_jsonform.models.fields.ArrayField(
                base_field=models.CharField(), blank=True, default=list, size=None
            ),
        ),
        migrations.AlterField(
            model_name="job",
            name="description",
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name="job",
            name="location",
            field=models.CharField(blank=True),
        ),
    ]
