# Generated by Django 5.2 on 2025-10-27 02:58

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("portfolio", "0004_rename_skill_technology_alter_job_options_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="project",
            name="technologies",
        ),
        migrations.AddField(
            model_name="project",
            name="tech_stack",
            field=models.ManyToManyField(blank=True, to="portfolio.technology"),
        ),
    ]
