# Generated by Django 5.2 on 2025-10-27 03:04

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("portfolio", "0005_remove_project_technologies_project_tech_stack"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="contact",
            options={
                "ordering": ["-created_at"],
                "verbose_name": "Contact Form Submission",
                "verbose_name_plural": "Contact Form Submissions",
            },
        ),
        migrations.AlterModelOptions(
            name="technology",
            options={"ordering": ["ordering"], "verbose_name_plural": "Technologies"},
        ),
        migrations.AddField(
            model_name="contact",
            name="created_at",
            field=models.DateTimeField(
                auto_now_add=True, default=django.utils.timezone.now
            ),
            preserve_default=False,
        ),
    ]
