# Generated by Django 5.2.7 on 2025-10-27 14:36

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("portfolio", "0006_alter_contact_options_alter_technology_options_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="project",
            name="image",
            field=models.ImageField(blank=True, upload_to=""),
        ),
    ]
