# Generated by Django 5.2.7 on 2025-10-27 15:14

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("portfolio", "0007_alter_project_image"),
    ]

    operations = [
        migrations.CreateModel(
            name="Content",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("is_published", models.BooleanField(default=True)),
                ("title", models.CharField(unique=True)),
                ("content", models.TextField()),
            ],
            options={
                "verbose_name_plural": "Content",
            },
        ),
    ]
