# Generated by Django 5.2.7 on 2025-10-27 23:17

import django_jsonform.models.fields
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("portfolio", "0008_content"),
    ]

    operations = [
        migrations.CreateModel(
            name="PersonalInfo",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("is_published", models.BooleanField(default=True)),
                ("name", models.CharField()),
                ("title", models.CharField()),
                ("email", models.EmailField(max_length=254)),
                ("phone", models.CharField(blank=True)),
                ("summary", models.TextField(blank=True)),
                ("street_address", models.CharField(blank=True)),
                ("city", models.CharField(blank=True)),
                ("state", models.CharField(blank=True)),
                ("zip_code", models.CharField(blank=True)),
                (
                    "links",
                    django_jsonform.models.fields.ArrayField(
                        base_field=models.URLField(),
                        blank=True,
                        default=list,
                        size=None,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "verbose_name": "Personal Information",
                "verbose_name_plural": "Personal Information",
                "ordering": ["-created_at"],
            },
        ),
    ]
