# Generated by Django 5.2.7 on 2025-10-29 16:16

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("portfolio", "0009_personalinfo"),
    ]

    operations = [
        migrations.AddField(
            model_name="technology",
            name="icon",
            field=models.CharField(blank=True),
        ),
    ]
